name: Main Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # add: lighthouse(?), a11y

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci && npm i -g @lhci/cli@0.8.x
      - name: Build site
        run: npm run build
      - name: Analyze with lighthouse
        run: lhci autorun

  # lints code
  # Need to lint manually because Next.js build only lints with eslint, not prettier
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint files
        run: npm run lint

  # runs all jest tests
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  # Next.js build includes typecheck
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Test build
        run: npm run build
